language: python
virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install python-lxml
install: 
  - pip install tox
script: tox
env:
  - TOXENV=py27
  - TOXENV=py27pg
  - TOXENV=flake8
